In [2]:
import jax
import jax.numpy as np

In [7]:
x = np.ones((3, 4))

In [8]:
x[np.arange(0, 2)]

Array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [12]:
np.take(x, np.arange(0, 2), axis=0)

Array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [15]:
np.mean(np.array([[0, 1, 2], [3, 4, 5]]), axis=-1)

Array([1., 4.], dtype=float32)

In [17]:
jax.random.split(jax.random.key(0), 3)

Array((3,), dtype=key<fry>) overlaying:
[[1797259609 2579123966]
 [ 928981903 3453687069]
 [4146024105 2718843009]]